import abdul from "/public/images/abdul.jpg"
import abdil from "/public/images/abdil.jpg"
import adila from "/public/images/adila.png"
import akif from "/public/images/akif.jpg"
import alif from "/public/images/alif.jpg"
import baehaki from "/public/images/baehaki.jpg"
import cinul from "/public/images/cinul.png"
import fajar from "/public/images/fajar.jpg"
import faqih from "/public/images/faqih.jpg"
import farhah from "/public/images/farhah.png"
import fathur from "/public/images/fathur.jpg"
import ghazi from "/public/images/ghazi.jpg"
import hanna from "/public/images/hanna.png"
import hedza from "/public/images/hedza.jpg"
import inas from "/public/images/inas.png"
import ayu from "/public/images/kaayu.png"
import kafin from "/public/images/kafin.jpg"
import azizah from "/public/images/kajija.png"
import kia from "/public/images/kakia.png"
import monit from "/public/images/kamonit.png"
import mutia from "/public/images/kamute.png"
import widya from "/public/images/kawid.png"
import nuy from "/public/images/maminuy.png"
import marwa from "/public/images/mawar.png"
import maul from "/public/images/mawl.png"
import ashma from "/public/images/mbaashma.png"
import murod from "/public/images/murod.jpg"
import nabila from "/public/images/nabila.png"
import nia from "/public/images/nia.png"
import oji from "/public/images/oji.jpg"
import rafa from "/public/images/rafa.jpg"
import sacil from "/public/images/sacil.png"
import sarah from "/public/images/sarah.png"
import sipkum from "/public/images/syifkum.png"
import taqi from "/public/images/taqi.jpg"
import tia from "/public/images/tia.png"
import fatim from "/public/images/timi.png"
import um from "/public/images/um.png"
import una from "/public/images/una.png"
import wafa from "/public/images/wafa.png"
import yanev from "/public/images/yanev.png"
import yaud from "/public/images/yaud.jpg"
import yuyun from "/public/images/yuyung.png"
import zaki from "/public/images/zaki.jpg"
import zakiyah from "/public/images/zakiyah.png"
import zharfan from "/public/images/zharfan.jpg"

export const profile = [
    {
        "id": 1,
        "name": "ABDULLAH MUHAMMAD",
        "nickname": "Bedul",
        "birth": "Malang, 22 October 2002",
        "dream": "Sustainability Engineer, Sustainability Consultant, Waste Management Expertise",
        "mainDream": "Waste Management Expertise",
        "about": "Abdullah is a last year student of Metallurgy and Materials Engineering from Universitas Indonesia who’s interested in sustainability engineer related topic, especially waste management. As a future materials engineer Abdullah believes that  all types of materials are a gift along with their own advantages and disadvantages uniqueness, the responsibility belongs to the materials engineer to find the best way to show the potential of a material through outs its life cycle in a way that creates a balance of nature for the next generation.",
        "achievement1": "Chairman of Majelis Permusyawaratan Mahasiswa (MPM) Metalurgi FTUI 2022",
        "achievement2": "Finalist of the Most Outstanding Student Leadership Category at FTUI 2023",
        "achievement3": "First Place Futsal Competition at Olimpiade Universitas Indonesia in 2022 and 2023",
        "education": "2020 - 2024: Metallurgy and Materials Engineering, Universitas Indonesia",
        "message": "Premis kalimatnya akan selalu tentang bersyukur telah dipertemukan kalian. Namun untuk susunan kalimatnya, biarlah tetap kosong dan akan selalu terbarui di dalam akal pikiran.",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/BMhBrw2ETYM?si=-1wkFODvNqtz2g7H\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/abdullaahmz\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/abdullahmza\/",
        "twitter": "#",
        "hobby": "Playing futsal, Reading.",
        "role": "Ksatria",
        "image": abdul,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 2,
        "name": "ACHMAD ABDILLAH PASHA",
        "nickname": "Abdil",
        "birth": "Depok, 6 April 2002",
        "dream": "WHO SEARO Regional Director, Global Health Policy Expert, Global Health Consultant Founder ",
        "mainDream": "WHO SEARO Regional Director",
        "about": "A highly motivated and prospectful future leader who are aiming to significantly making impact in global health policy worldwide.",
        "achievement1": "Indonesian International Student Mobility Awards (IISMA) Awardee 2023 to Universiti Malaya",
        "achievement2": "Finalist of the Most Outstanding Student in Faculty of Public Health Universitas Indonesia 2023",
        "achievement3": "General Leader of Nuansa Persaudaraan Islami (Nurani) FKM UI 2023",
        "education": "2020 - 2024: Occupational Health and Safety, Universitas Indonesia",
        "message": "Dearest Ksatiara\n\nThank you is never enough to express my gratitude to get to know all of you better. Having you all in my long-life learning journey are blessings that Allah has given to me, seriously. Thanks for everything, Ksatiara!\n\nWishing a remarkable moments for all of us! Pls stay connected each other after this^^",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/JGkcKIwPRyI?si=skDbvzaNwkl_RdT0\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/abdillahpashaa",
        "linkedin": "https:\/\/www.linkedin.com\/in\/achmad-abdillah-pasha-02a4ab207?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        "twitter": "#",
        "hobby": "Writing, Traveling, Netflixing",
        "role": "Ksatria",
        "image": abdil,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 3,
        "name": "ACHMAD RIZKI BAEHAKI",
        "nickname": "Baehaki",
        "birth": "Jember, 13 Mei 2002",
        "dream": "Data Scientist, Businessman, Filantropis",
        "mainDream": "Filantropis",
        "about": "I am someone who is naturally curious about unique and challenging problems, particularly those in the realm of social dynamics and community engagement. My passion extends to exploring various facets of Data Science. With a profound ambition to pursue my dreams and positively impact others, I embrace imperfection in the journey, valuing progress above perfection, as it continually refines and betters me.",
        "achievement1": "Alhamdulillah, there has been significant progress in many areas, especially in embodying the vallues of ROOM PK (Rendah Hati, Objektif, Open Mind, Moderat, Prestatif, Kontributif)",
        "achievement2": "null",
        "achievement3": "null",
        "education": "Statistics, Universitas Indonesia",
        "message": "Mau nyampein lirik ini:\nSemua mimpi tinggi dan segala drama\nDijadikan canda, dikeluh bersama\nTerkadang-kadang mata bicara\nSeakan-akan semua rahasia\nOh, kebodohan antara kita jadi kenangan manis🥹\n\nTuk sementara, sampai berjumpa\nBersama-sama, bercanda lagi\nKenangan manis di hari ini\nJadi alasan untuk kembali😊\n\nSemoga sukses semua di masa depan guys, gue berharap juga silaturahmi kita ga akan pernah putus sampe kapanpun.",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/uOLCUfv9Wg4?si=lrKg_t0GEo3q8hLZ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/achm.rizki?igsh=eXpqMmE0dzZyazlw",
        "linkedin": "https:\/\/www.linkedin.com\/in\/achmadrizkibaehaki",
        "twitter": "#",
        "hobby": "Playing Badminton, Cycling, Adventure",
        "role": "Ksatria",
        "image": baehaki,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 4,
        "name": "ADILA RAFAHIYA",
        "nickname": "Adila",
        "birth": "Yogyakarta, 4 Mei 2003",
        "dream": "Chief Executive Officer, Marketing Specialist",
        "mainDream": "Chief Executive Officer ",
        "about": "I'm sure you know me so well guys:D",
        "achievement1": "Market Insight Customer Value Management Intern MBKM x Telkomsel Batch 6",
        "achievement2": "1st Winner of DIGIVATHON UPI 2023",
        "achievement3": "2nd Winner of National Marketing Plan CFEST UMY 2023",
        "education": "2021 - 2025: Management, Universitas Indonesia",
        "message": "It's never too late to start creating the life you want:D\nYou should know that meeting you was the best thing in my life. Thanks, dude!",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/OKZs848vrY0?si=ROm386qTRy3h12I6\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/adilaarafa\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/adila-rafahiya\/",
        "twitter": "#",
        "hobby": "Challenge myself",
        "role": "Tiara",
        "image": adila,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 5,
        "name": "AHMAD MUFID DHIYA'UDIN",
        "nickname": "Yaud",
        "birth": "Jakarta, 14 October 2002",
        "dream": "Geothermal Engineer, Sustainability Analyst, Energy Transision Analyst",
        "mainDream": "Geothermal engineer",
        "about": "As an adaptable individual with a diverse range of ideas and a talent for active listening, my passion for social impact has driven my fascination with geothermal energy. I aspire to establish myself as a foremost authority on Indonesian geothermal affairs. In this endeavor, I intend to utilize my versatile background to pioneer innovative solutions that expedite Indonesia's shift towards clean energy",
        "achievement1": "Finalist of the Green Influencer Award in Depok",
        "achievement2": "Finalist for Young Leaders for Climate Award ",
        "achievement3": "Created Merakit Asa",
        "education": "2021 - 2025 : Geophysics, Universitas Indonesia",
        "message": "Salah satu kehormatan dan kebanggaan bisa bergabung dan berkembang bersama teman-teman Ksatiara, gue percaya tidak ada suatu hal yang kebetulan di dunia ini, dan semangat untuk para pemimpi(n) untuk mencapai mimpinya masing-masing",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/_klW23lpCkw?si=xXv8ebmP129jPAsG\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/mufid.yaud?igsh=bWt3MHJ2azVvYnMw",
        "linkedin": "https:\/\/www.linkedin.com\/in\/ahmad-mufid-dhiya-udin?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        "twitter": "#",
        "hobby": "Playinh football, badminton, and hiking",
        "role": "Ksatria",
        "image": yaud,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 6,
        "name": "AMINAH ZAHRAH",
        "nickname": "Min",
        "birth": "Osaka,  3 January 2001",
        "dream": "Dentist, Oral and maxillofacial surgeon, health researcher",
        "mainDream": "Dentist",
        "about": "Aminah is fueled by an insatiable thirst for knowledge and continually seeks opportunities for growth. With unwavering determination, she tirelessly pursues her dreams of becoming a renowned dentist specializing in oral and maxillofacial surgery, as well as an esteemed health researcher dedicated to societal welfare. Despite her penchant for independence, she seldom reveals her struggles to others, often prioritizing their needs above her own. While regarded for her altruism, she remains guarded about her emotions, making it challenging for others to connect with her on a deeper level.",
        "achievement1": "1st place in International Dental E-Quiz at IIUM 2023",
        "achievement2": "1st place in the Dental Quiz Competition Densmart FKG Trisakti 2023",
        "achievement3": "Participant of ASEAN+ Youth Summit 2023",
        "education": "2020-2024: Dentistry, Universitas Indonesia",
        "message": "Dear ksatiara XI, \nthank you for being the family I never knew I needed, \nfor being an inspiration to move forward, \nfor creating lots of opportunity of new experiences, for teaching so much about life,\nfor giving so much love as friends in need and friends indeed.\n\nI may lack a lot and made mistakes as long as we were together for the past 2 years,\nI may hurt you without noticing it,\nI may not give the same amount of love I received,\nBut deep down I hope that this ending means a new start that create bonds stronger than ever and to not forget each other about how much we treasure one another. \n\nHappy graduation and may Allah show you the brightest path for what coming next. See you at the top❤️",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/SnFsfQ754To?si=cTALOXt6l98KvIxn\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/aminahzhr?igsh=MXM0czF5ZzJ5NXY5dQ==",
        "linkedin": "#",
        "twitter": "#",
        "hobby": "Reading books, novels, and phone",
        "role": "Tiara",
        "image": abdul,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 7,
        "name": "ASHMA’ MAKARIM ZAFIROH",
        "nickname": "Ashma",
        "birth": "Magelang, 11 September 2001",
        "dream": "Shariah Auditor, Entrepreneur",
        "mainDream": "Shariah Auditor",
        "about": "A learner, hardworker, and entrepreneur",
        "achievement1": "Audit Internship at KPMG Indonesia ",
        "achievement2": "null",
        "achievement3": "null",
        "education": "2020 - 2024 : Accounting, Universitas Indonesia",
        "message": "Hai pemimpin muda!\nPerjuangan dalam hidup tidak akan pernah berhenti, istirahat bukan berarti menyerah. \nTetap semangat, konsisten, dan fokus terhadap tujuanlah yang akan membantu kita bertahan dalam proses perjuangan hidup ini. Tentu, berdoa kepada Allah agar keberkahan selalu menyertai hidup kita adalah sebuah keharusan. \nInhale, exhale, take a deep breath, exhale. \nSemangat pejuang!\n\nTerima kasih sudah memberikan warna baru di masa-masa terakhir aku berkuliah <33",
        "visdream": "null",
        "instagram": "https:\/\/www.instagram.com\/ashmmkrm\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/ashmamz\/",
        "twitter": "#",
        "hobby": "Reading book",
        "role": "Tiara",
        "image": ashma,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 8,
        "name": "AYU WULANDARI",
        "nickname": "Ayu",
        "birth": "Jepara, 8 March 2002",
        "dream": "Mother & Child Nurse Specialist, Clinic Owner, Nursepreneur",
        "mainDream": "Clinic Owner",
        "about": "As a final year student at the Faculty of Nursing, University of Indonesia, I have actively engaged in diverse community service initiatives spanning education, social welfare, and healthcare. My academic pursuits align seamlessly with my interests in these fields, particularly in areas such as pediatric nursing, family dynamics, and community health. With a keen ability to adapt and a thirst for knowledge, I am eager to collaborate with others and tackle challenges head-on. My dedication to serving my country's healthcare sector drives my aspiration to become a skilled pediatric nurse. Furthermore, I envision establishing an independent clinic specializing in parenting and maternal and child care, demonstrating my commitment to holistic healthcare delivery.",
        "achievement1": "Online Student Exchange at Hanze University Groningen, Netherlands, 2023",
        "achievement2": "Semifinalist in the Nursing Olympiad at Faaculty of Nursing Universitas Airlangga, 2023",
        "achievement3": "3rd place in the National Poetry Creation Competition with Oxygenbooks Publisher, 2021",
        "education": "2020 - 2025 : Nursing, Universitas Indonesia",
        "message": "Terimakasih sudah menjadi bagian dari cerita baik dan perjuangan Ayu selama ini. Semoga kita selalu bisa mengusahakan kebaikan dan kebermanfaatan untuk diri sendiri dan banyak orang. Sukses terus untuk kalian orang orang hebat",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/FrK9NloU1MA?si=HaFrsqc_5s0icOpI\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/ayu_wulan8",
        "linkedin": "https:\/\/www.linkedin.com\/in\/ayu-wulandari-430001299\/",
        "twitter": "#",
        "hobby": "Run",
        "role": "Tiara",
        "image": ayu,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 9,
        "name": "AZIZAH ASHRI MUFLIHAH",
        "nickname": "Azizah",
        "birth": "Jakarta, 31 October 2002 ",
        "dream": "Hospital Owner & Director, Pedodontist, Content Creator  ",
        "mainDream": "Hospital Owner & Director ",
        "about": "A cheerful woman who had big dream to bring healthy smiles to Indonesian children through her contribution in the health and social fields. She also wants to build an Islamic-based hospital with the best moslems health practitioners across the country. Big goals are her favourite challenge, although it's hard to achieve but she always believe when she trust in herself that she can do it, she's halfway there. ",
        "achievement1": "2nd Most Outstanding Students FKG UI 2023 ",
        "achievement2": "Chairman of BPI FKG UI in 2023 ",
        "achievement3": "Winner of the consolation prize of oral presentation competition by the Malaysian Association of Dental Public Health Specialist in 2024 ",
        "education": "2020 - 2026 : Dentistry, Universitas Indonesia ",
        "message": "Dear ksatiara, since the first day I met all of you, I know that you guys will be some people who are very meaningful to my life. After two years living together, it's the truth that I proved by my ownself. \n\nChoosing RK as my second home means agreed to have new 50+ family members who will be my 24\/7, and indeed, it was what I looked for. That time, I remember how hard it is to fight alone. Having a lot of dreams without knowing the steps how to make it real. Living in a circle who didn't have same frequencies about the \"dream concept\" and slowly affect my trust to my own dreams.\n\nActually it's the same condition : I'm dreaming, but the difference is, since I entered RK, i'm not a single dreamer, but I'm part of a crazy-highdreamer-family.  Here, I never felt my big was too big. In the opposite, i realized that sometimes my efforts were too weak, and ksatiara became my motivation to fight harder and stronger. \n\nTo all of you who read this, I just want to say that living 2 years with all these giants are my biggest gratitude. Without them, maybe I'm not who I am today. So, thankyou so much for everything. \n\nIt might be only 2 years living and dreaming together, but I believe it takes a lifetime to make it real and continue journey for our biggest dream : going to Jannah together. \n\nMay allah bless our life always, aamiin allahumma aamiin ",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/32HO5LDWoIc?si=Ib-u-4basjE5gUvq\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/azizahashrii ",
        "linkedin": "https:\/\/www.linkedin.com\/in\/azizah-ashri-muflihah-2533a929a\/",
        "twitter": "#",
        "hobby": "Story telling, reading book ",
        "role": "Tiara",
        "image": azizah,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 10,
        "name": "AZRA MEUTIA NUJUD",
        "nickname": "Tia",
        "birth": "Jakarta, 8 Agustus 2002",
        "dream": "Process Engineer, Writer",
        "mainDream": "Process Engineer",
        "about": "As the eldest of five siblings, my inclination towards independence is deeply ingrained. Guided by my INFJ-T personality type and fueled by my love language of quality time, I am driven by a vision to maximize the potential of waste as a renewable energy source. My dream is to be among the pioneers who harness innovative solutions to transform waste into energy, contributing significantly to sustainability efforts and environmental conservation.",
        "achievement1": "2nd place winner in the Musabaqoh Hifdzil Quran competition FTQO in 2022",
        "achievement2": "Member of the Top 50 Essay at the HK ExperTalk Competition",
        "achievement3": "3rd place winner in the Musabaqoh Hifdzil Quran Competition FTQO in 2023",
        "education": "2021 - 2025: Chemical Engineering, Universitas Indonesia",
        "message": "Hai, ksatiara!\nMakasi banyak yaa udah mewarnai hari-hari aku yang gitu-gitu aja, hehe. Kayaknya setiap aku denger lagu monokromnya tulus bakal inget kalian terus, deh. Mulai dari ucapan ulang tahun yang gabakal aku lupa karena se-spesial itu, momen malam apresiasi dengan kerandoman game-nya, dan segala naik turun hidup yang kita laluin bareng-bareng. Please, tetap inget itu semua yaa :\">\nSemoga kemanapun semua perjalanan kita bermuara, itu jadi takdir terbaik kita dan see you on top and Jannah <3",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/eJ4zCP26L8E?si=Ol8w5nuAQ-i42kdg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/azra_njd",
        "linkedin": "https:\/\/www.linkedin.com\/in\/azra-meutia-nujud-6a2a4716b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        "twitter": "#",
        "hobby": "Watching movies and kdrama",
        "role": "Tiara",
        "image": tia,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 11,
        "name": "BANGUN FARIQOH SA’ADAH",
        "nickname": "Yuyun",
        "birth": "Kebumen, 13 May 2003",
        "dream": "Environment Consultant, Civil Servant, Project Manager",
        "mainDream": "Civil Servant",
        "about": "Bangun Fariqoh Sa'adah, affectionately known as Yuyun, is an undergraduate student enrolled in the Environmental Engineering program at the Faculty of Engineering, University of Indonesia. With a proven track record in leadership and adept problem-solving skills, she excels both in team environments and when working independently. Yuyun's aspiration to serve as a civil servant was put to the test when she assumed the role of General Leader of MPM FTUI 2024. Beyond her academic pursuits, she possesses a keen interest and aptitude in the arts, including singing, painting, and graphic design.",
        "achievement1": "Chairman of MPM FTUI in 2024",
        "achievement2": "Winner of the National Student Choir Competition organized by Puspresnas",
        "achievement3": "Outstanding Student in the Leadership Category",
        "education": "2021 - 2025: Environmental Engineering, Universitas Indonesia",
        "message": "Setiap pertemuan pasti ada perpisahan, walaupun kita tidak pernah tahu kapan perpisahan itu terjadi. Tapi, di tempat ini, aku menemukan banyak hal yang pada kenyataannya tidak ingin perpisahan itu menghampirinya. Terima kasih kepada RK yang telah memberikan kesempatan dan kepercayaan kepadaku untuk menjadi Awardee-nya. Terima kasih abang dan kakak SPV yang sudah bersaabar menghadapi perlakuan A-Z kita semua. Terima kasih kepada teman-teman Ksatiara yang sudah mengizinkan aku menjadi bagian dari perjalanan hidup kalian. Di sini aku belajar banyak hal tentang kehidupan, bagaimana rasanya sedih, senang, sabar, kesal, dan semua emosi dirasakan bersama-sama. Terima kasih telah memberiku arti kehidupan yang hanya satu kali kita alami. Semoga, perpisahan kali ini tidak menghalangi kita untuk bertemu kembali di surga-Nya nanti. Semoga kita semua masih bisa saling berkomunikasi dan memberi kabar satu sama lain. Ditunggu undangan nikahnya satu sama lain Ksat, Tiara, hehe. Maaf apabila selama kenal denganku banyak hal yang kurang berkenan dan menyakiti hati, semoga kita semua sudah saling memaafkan ketika lulus dari sini, biar ga ada dosa yang tertahan juga. Kita usahakan saudara sampai surga itu. Sekali lagi terima kasih dan lov u Ksatiara XI! <3",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/WTZ5X_lI50M?si=aXwiPeCREQ8P4eF5\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/bangunfs13\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/bangunfariqoh\/",
        "twitter": "#",
        "hobby": "Singing, Playing Badminton, and Painting",
        "role": "Tiara",
        "image": yuyun,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 12,
        "name": "FAQIH M TRISNA ROMADHON",
        "nickname": "Trisna",
        "birth": "Kebumen, 4 December 2001",
        "dream": "Graphic Designer, Social Media Officer, Collumnis",
        "mainDream": "Graphic Designer",
        "about": "A dedicated lifelong learner, specializing in article writing and graphic design, with a strong background in implementing historical methods through written content at the university level. Committed to leveraging skills and experience in media and design through volunteer work with diverse organizations and event committees. His skills in graphic design are certified by Adobe Photoshop and BNSP. Get to know his project at Vilutions (if possible add hyperlink https:\/\/www.instagram.com\/vilutions) and HiStory Website. (hyperlink https:\/\/faqihmtr.wixsite.com\/history\/mukaddimah)",
        "achievement1": "Daesang Global Leader: Master of Respect",
        "achievement2": "Certified Professional in Visual Design using Adobe Photoshop and Certified Junior Graphic Designer by BNSP RI",
        "achievement3": "Best Social Entrepreneurship Project Presentation on 11 Days ASEAN Youth Volunteer Programme 2023 Universiti Kebangsaan Malaysia X Universitas Gadjah Mada",
        "education": "2020 - 2024: History, Universitas Indonesia",
        "message": "I just can say thanks and my apology.\n\nDidn't ask for more than a free dorm but Allah gave me a bunch of supportive systems here. I am fully aware that I'm such a moody, and low friendship person but they accept me as one of them. Despite a love-hate relationship with RK that every Ksatiara can tell, I'm sure this is the most valuable experience I can gain during my college era. I know most of Ksatiara will say this is just another start and not our end. But I'll keep remembering this moment and remain gloomy and emotional.\n\nDon't mind me, I'm ok.\n\nWe should gather again without exposing each other. With a dress code, food, fun games, two unprofessional MCs, a screen, and a projector in front of us. Shall we?\n\nP.S. Probably u guys missing us(?) go check our yearbook for further memories!!",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/eJT8LxiRlgY?si=0MeOu1Jfya1XK41S\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/faqihmtr\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/fmtr\/",
        "twitter": "https:\/\/twitter.com\/faqihmtr",
        "hobby": "Listening to tropical and dance music",
        "role": "Ksatria",
        "image": faqih,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 13,
        "name": "FARHAH NASHRILLAH",
        "nickname": "Farhah",
        "birth": "Johor Bahru, 24 March 2002",
        "dream": "Content Creator, Entrepreneur, Environmental Activist",
        "mainDream": "Entrepreneur ",
        "about": "Hi!!! Farhah stands for happiness in arabic, and that’s what keeps me alive 🤭🚶‍♀️💙 i am enthusiast in eye-pleasing things, beauty, mindfulness, human interaction, and how to keep nature’s balance through small steps in sustainability 🌱🐢 I always looking for genuine happiness, laughter, and love to share with others and the bigger world <3 ",
        "achievement1": "IISMA awardee to Universiti Sains Malaysia in 2023",
        "achievement2": "Best Student Ambassador of Surplus Indonesia ",
        "achievement3": "null",
        "education": "2020 - 2024 : Environmental Health, Universitas Indonesia",
        "message": "tetap bermimpi setinggiiii langiiit dan berharap kepada Allah yang Maha Punya Segalanya! Karena mimpi dan harapan itulaaah yang jadi bahan bakar kita hidup di dunia, sampai nanti akhirnya ‘istirahat’ di akhirat. INGET INGET AKU YAH KLO MASUK SURGA🧎‍♀️mau diajak seneng di dunia dan di akhiraat",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/4PX4pL06k9I?si=EqXaISVUOOjvzyna\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/farhahen",
        "linkedin": "https:\/\/www.linkedin.com\/in\/farhah-nashrillah?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
        "twitter": "#",
        "hobby": "Reading Booksss, creating content",
        "role": "Tiara",
        "image": farhah,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 14,
        "name": "FATIMAH AZ-ZAHRA M P",
        "nickname": "Fatim",
        "birth": "Garut, 7 April 2004",
        "dream": "Metallurgist, Writer, BUMN Commisioner",
        "mainDream": "Metallurgist",
        "about": "An Ambivert(?) girl with great passion in environmental and energy transition issue in Indonesia. Have a dream to optimizing material resources in Indonesia by energy transition. Love to expand her insight and creative thinking by building connection with communities that in line with her interest. Being a simple, efficient but wise can be seen in her character. ",
        "achievement1": "Top 68 Energy Founder at Pertamuda 2023",
        "achievement2": "Secretary-General of MPM FTUI in 2024",
        "achievement3": "Top 10 Essay team in National Student Conference Econeering FTUI ",
        "education": "2021 - 2025: Metallurgy and Material Engineering",
        "message": "\"Terimakasih\", \"Maaf\", dan \"Selamat\". \nTerimakasih telah mengisi memori yang berharga di dalam hidup ku. Maaf karena masih banyak sekali kekurangan diri ini yang mungkin memberikan kenangan kurang baik. Selamat atas kelulusannya dan semoga selalu menyala di setiap langkah baik kita semua. Jangan pernah lupa bahwa rumah kita bersama ini, memang saat ini menjadi rumah singgah selama kita mahasiswa. Tapi segala kenangan, pembelajaran, dan pengalaman yang diberikan oleh rumah singgah ini sebaiknya tetap tertanam dalam diri kita bersama. ",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/fatimahamp_\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/fatimahamp\/",
        "twitter": "#",
        "hobby": "Take a walk",
        "role": "Tiara",
        "image": fatim,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 15,
        "name": "HANNA PUTRI PERTIWI",
        "nickname": "Hanna",
        "birth": "Batusangkar, 31 January 2002",
        "dream": "Translator, interpreter, fulltime learner",
        "mainDream": "Translator",
        "about": "A creative and open-minded person with focused skills in languages, digital marketing, social research, and related fields. She has professional experience as a content writer, translator, and B2B corporate sales . She is also willing to adapt to new circumstances, loves to work on the team, and gain new experiences.",
        "achievement1": "Revenue-Corporate Sales Intern MSIB x Shipper Batch 6",
        "achievement2": "Top 5 Finalist of UPCOME 2.0 Business Plan Competition at UPN Veteran Jakarta in 2023",
        "achievement3": "1st Place Winner of the Research Student Project Competition (PKM-RSH) at Universitas Indonesia in 2023",
        "education": "2021-2025: English Studies and Literature, Universitas Indonesia",
        "message": "coming soon ",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/hannaputri.p",
        "linkedin": "http:\/\/www.linkedin.com\/in\/hanna-putri-pertiwi",
        "twitter": "#",
        "hobby": "Reading, creating Spotify playlist",
        "role": "Tiara",
        "image": hanna,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 16,
        "name": "HEDZA FADLI ROBBINA",
        "nickname": "Hedza",
        "birth": "Jakarta, 26 September 2002",
        "dream": "Public Government, Teacher, Hafizhul Quran",
        "mainDream": "Public Government",
        "about": "Public governments who have led administrative governments at the city, provincial, and national levels. Have expertise in the fields of education, food security, and genetic product engineering. ",
        "achievement1": "Student Affairs Coordinator at BEM UI in 2024",
        "achievement2": "Participant of the Hyflex International Exchange Program at Nagasaki University, Japan",
        "achievement3": "Head of Himpunan Mahasiswa Departemen of Biology in 2023",
        "education": "2021 - 2025: Biology, Universitas Indonesia",
        "message": "Dear Ksatiara,\n\nKapanpun kalian mebaca pesan ini, 1 tahun, 5 tahun, 10 tahun, 30 tahun yang akan datang. Dimanapun itu. Di belahan benua manapun, di musim apapun, pagi, siang, atau malam.  Bersama siapapun kalian saat ini. Gue berharap kalian sudah berada di titik saat kalian melihat ke belakang, kalian bangga dan bersyukur atas jalan yang sudah kalian lewati selama ini. Perkenalkan kembali gue Hedza, salah satu dari kalian yang menjadi bagian dari pemimpi(n) yang diinkubasi di rumah yang sama, Rumah Kepemimpinan. Salam hormat untuk kalian semua orang orang hebat.\n\nSalam hangat dan rasa syukur tak ternilai,\ndari masa lalu yang membanggakan,\n28 April 2024,\n\nHedza Fadli Robbina.",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/hedzafr",
        "linkedin": "https:\/\/www.linkedin.com\/hedza-fadli-robbina-\/",
        "twitter": "https:\/\/x.com\/primacyfromgod",
        "hobby": "Traveling around the world",
        "role": "Ksatria",
        "image": hedza,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 17,
        "name": "HELMA RIZKIANA",
        "nickname": "Kiaa",
        "birth": "Lombok, 26 September 2001 ",
        "dream": "Akademisi, Linguis, Aktivis Tuli",
        "mainDream": "Akademisi ",
        "about": "I'm pretty girl who love to share loves",
        "achievement1": "Top 5 Finalist in the Youth Competition 2023 by CIAS ",
        "achievement2": "Awardee of Bakti Asa UI Scholarship ",
        "achievement3": "Awardee of Rumah Kepemimpinan Scholarship (Semsters 1-3)",
        "education": "2020–2024: Indonesian Literature, Universitas Indonesia sbrnnya ",
        "message": "Walau sebenarnya banyak, tapi ini sudah mendesak. Jadi kubiarkan saja baik-baik yang tak disebutkan di sini selalu tersampaikan dalam doa. \n\nKsatiara 11, \nKalian harus tahu posisi kalian dalam hati maupun hidupku. \n\nSangat berarti. Sangat bermakna. \nKalian banyak mengajarkanku dan memperlihatkan kepadaku cara-cara untuk mencintai dengan tidak biasa atau sekedar saja. \n\nKalian mengajarkanku bahwa kekurangan orang lain bukanlah untuk dibicarakan, tapi untuk dibantu agar disupport sehingga ia bisa berjalan bersama yang lain. \nKalian membuatku semakin percaya bahwa sosok muslim yang ideal dan teladan hebat kehidupan pada masa kini dan masa depan itu benar-benar ada. \n\nDan pastinya ketulusan, cinta, pengorbanan, pengertian, dan segalanya selalu tercurahkan dengan berlimpah. \n\nTerima kasih untuk selalu menganggapku juga yang lainnya sama-sama berarti. \n\nUntuk segala yang baik, semoga selalu terjaga dan semakin luas serta banyak. \n\nDan untuk segala kurangku selama kita bersama, mohon maafkan aku dengan segala ikhlasmu. \n\nSemoga kita bisa bertemu kembali di surga, aamiin. ",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/MFBVeNdw7SI?si=C_3g4Jk3bu7arL6z\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/rzkianaaah",
        "linkedin": "https:\/\/id.linkedin.com\/in\/helma-rizkiana-125a73267 ",
        "twitter": "#",
        "hobby": "Menulis sastra, berkhayal, & makan yang manis ",
        "role": "Tiara",
        "image": kia,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 18,
        "name": "INAS HAYA RAHMAWATI FADHILLA",
        "nickname": "Inas",
        "birth": "Kebumen, 11 February 2003",
        "dream": "Creative Director, Campaign Strategist",
        "mainDream": "Campaign Strategist",
        "about": "Hi! I'm Inas, passionate about arts, culture, and creative marketing. Currently, I'm immersing myself in studying advertising strategy and marketing communication to pursue my future career aspirations. I am focusing my studies on advertising strategy and marketing communication for my future career. I have some experience in several fields, such as public relations, content planning, event organizer, and community relations, especially in internal relations. I like to try and learn new things, until finally I can become a person who can share some benefits with others using my abilities and knowledge<3",
        "achievement1": "2nd place Marketing Plan Competition",
        "achievement2": "Favorite winner of the Video Competition",
        "achievement3": "null",
        "education": "2021 - 2024: Communication Sciences, Universitas Indonesia",
        "message": "Ketika diminta untuk menulis pesan, jujur aku ga kepikiran mau nulis apa.\nTapi intinya 2 tahun bersama kalian menjadi 2 tahun yang berharga. 2 tahun yang kubangga. 2 tahun yang sebenarnya aku ingin selalu\n\nterima kasih atas semua kisah kasih bersama kalian,\n\"When I'm down and out\nAnd feel like there is nothing left for me\nYou save me\nOoh, I feel nothing without you\nOoh, there'd be no song without you, without you\"\n(no song without you - HONNE)",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/0SajeZXfQAo?si=jq8DVVY2i9oPqcEV\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/inasharf\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/inashaya\/",
        "twitter": "#",
        "hobby": "Riding motorcycle and traveling!",
        "role": "Tiara",
        "image": inas,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 19,
        "name": "KAMILA NURHUSNA ",
        "nickname": "Una ",
        "birth": "Bekasi, 27 June 2002",
        "dream": "Environmental Consultant, Ecopreneur, CEO Woman ",
        "mainDream": "Environmental Consultant ",
        "about": "Una is long life learner (nyusul deh masih mikir)",
        "achievement1": "Finalist of the Most Outstanding Student in Environmental and Social Fields",
        "achievement2": "Winner of Daily Vlog Competition held by UKKI An-Nur ",
        "achievement3": "Awardee of Community Service Grant Funding held by Universitas Indonesia  ",
        "education": "2020 - 2024: Environmental Engineering, Universitas Indonesia",
        "message": "Hai tiara, perjalanan 2 tahun bersama kemarin ternyata secepet itu ya? nyatanya keputusan besarku untuk mengenyam asrama kedua kalinya bukanlah hal yang aku sesalkan [despite of serangan tomcat :')] \nAku selalu menghargai setiap momen yang kita lalui, dari berantem sampe akur, dari masalah perasramaan sampai agenda. Suka pokoknya kalau ada yang rame-rame. Kalian gak cuma jadi rumahku untuk beristirahat tapi juga sebagai pendorongku untuk terus maju. \nKalian semua wanita keren binti independent tii, percayalah! Kalau ada yang mau nyakitin kalian, inget ya kita punya skill naikin galon sampe lantai 4. Kalian hebat dimata orang yang tepat. \n\nHalo Big Ksatiara, dinamika 2 tahun asrama jujur sangat berwarna, walaupun beberapa tahun lagi kenangan itu akan sedikit banyak terhapus dengan cerita baru dari masing-masing perjalanan hidup kita. Yaaa gapapa sih, ini kan tujuan dari yearbook, biar ada momen nostalgia. Pokoknya, kan kutunggu kabar kehidupan kalian! ",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/-clLn0C5pSY?si=MdGUK6L6jSuwqJRV\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/kamilauna",
        "linkedin": "https:\/\/www.linkedin.com\/in\/kamilanurhusna",
        "twitter": "#",
        "hobby": "Tersenyum",
        "role": "Tiara",
        "image": una,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 20,
        "name": "M. FATHUR RAHMAN",
        "nickname": "Thur",
        "birth": "Bagan Batu, 20 December 2002",
        "dream": "Econom, Senior Analyst Researcher, Lecturer",
        "mainDream": "Econom",
        "about": "Fathur is a small size of organic components Allah created to help human kinds in several way using econometrics model. He's an ambiguous person that had still been looking towards about his future.\n\nBut, her mom always said no matter what he's doing, she knows that his existence always to be what she proud of. At any time, i'll do whatever she loves me to do, and no matter what i'm doing, she'll be the one of future of me she always wanted. ",
        "achievement1": "Second Place and Best Case Study of International Paper Competition in the 21st of Economix 2023",
        "achievement2": "3rd olace of National Energy Business Case Universitas Gajah Mada ",
        "education": "2021 - 2023: Economics, Universitas Indonesia",
        "message": "Pertama kali masuk pintu RK, gw melihat kalian itu biasa saja. Selama berada di masa keemasan SMA, gw terperangkap dalam memori itu dan menganggap diri gw adalah yang terbaik dibanding kalian. Gw hidup damai, nyaman, dan menikmati masa\" itu. Namun, setelah mengenal kalian semua, gw ga merasakan kedamaian lagi.\n\nKalian memaksa gw untuk tidak hidup nyaman lagi. Gw lelah melihat kalian semua. Gw lelah melihat kalian mengikuti kegiatan kampus tiada hentinya dengan passion yg kalian tekuni.  Karena kalian gw melepas zona nyaman ini. Gw ga bisa gini\" terus melihat kalian yg terus berprestasi dan memberi sumbangan ke masyarakat tanpa balas jasa seperti ituuu. \n\nGw merasa kecil di hadapan kalian semua. Gw ga bisa diam sampai disini, gw ikutin semua kegiatan yang gapernah gw tau dg 0% pengalaman. Karena kalian, Gw mulai ikut pengmas, juara kompetisi internasional, dll. Percayalah, itu semua karena kalian. Kalian pembangkit gw, kalian penyelamat gw, kalian yg buat gw sampai di titik ini. Percayalah, tanpa adanya kalian, secara langsung ataupun ga langsung, kalian sangat bermakna dan bakal trus membekas di memori gw.\n\nTerima kasih ksatiara",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/PY35CDoWJoo?si=WI70w6XlbwkRPC2s\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/fathuur12",
        "linkedin": "https:\/\/www.linkedin.com\/in\/frfathurrahman",
        "twitter": "#",
        "hobby": "Doing exercise and playing mobile legend",
        "role": "Ksatria",
        "image": fathur,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 21,
        "name": "MARWA ALIIFAH MUTHMAINNAH",
        "nickname": "Marwa",
        "birth": "Bogor, 4 March 2002",
        "dream": "Clinical Psychologist, Academics, a Quran Scholar",
        "mainDream": "Clinical Psychologist",
        "about": "An aspiring clinical psychologist (not HRD!) with a passion for research in the field of Islamic psychology. I would love to look at Psychology from a Quranic lense and implement it in my family as well as the wider community. One quote that I live by is that everything happens for a reason and that God's plans are better than our dreams. Things that help me keep going are prayers, family & friends, and a cup of iced coffee :))",
        "achievement1": "Presenter in the Psychology from the East, Psychology from the West International Conference 2023 on Political Efficacy",
        "achievement2": "Best Scientific Paper on Sexual Education in Indonesia, Faculty of Psychology 2021",
        "achievement3": "Copper Certificate for Cambridge Chemistry Challenge, University of Cambridge 2019",
        "education": "2021 - 2025: Psychology, Universitas Indonesia",
        "message": "Dear Ksatiara, aku sangat bersyukur Allah telah mempersatukan kita selama 2 tahun ke belakang. Sayangnya, saat ini kita telah tiba di persimpangan dan harus berpisah untuk memilih satu dari banyaknya jalan kehidupan. Aku yakin akan sedikit menyeramkan, tapi aku juga percaya bahwa kalian akan bersinar dimanapun kalian berada dengan warna-warna yang berbeda. Ketika menghadapi rintangan, tolong ingat bahwa ada Ksatiara yang selalu siap untuk mengulurkan tangan. Selain itu, jangan lupa jugaa untuk tulus berdoa kepadaNya dan mengisi link form konseling Makara ^^ : https:\/\/konselingmakaraui.wixsite.com\/seekhelp\n\nIntinya, terimakasih banyak sudah menjadi tempatku berkembang dan memberikan banyak kehangatan. Terimakasih juga sudah mau bersabar dengan ratusan BC LEAP dari awal pembinaan. Maafin aku yaa atas semua kata-kata atau sikap yang kurang mengenakkan di hati kalian. Selain tagihan kas, piket asrama, dan piket angkat galon, aku akan merindukan semua kegiatan kita di asrama. Aku berharap, meskipun tidak ada lagi apel, tubul, agenda malam, 1on1, dan TTA, kita tetap dapat menjaga semangat kita untuk berkontribusi terhadap bangsa dan agama. Semoga ikhtiar kita dapat menjadi bekal yang mengantarkan kita semua pada pertemuan abadi di surgaNya nanti. Sehat-sehat ya Ksatiara! Doaku menyertai di setiap langkah yang kalian jalani <3",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/G1CvtRnNnPg?si=BRBwWppTc-LnI44D\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/marwamuth_",
        "linkedin": "https:\/\/www.linkedin.com\/marwa-aliifah-muthmainnah",
        "twitter": "#",
        "hobby": "Reading heartfelt quotes and messages + creating them<3",
        "role": "Tiara",
        "image": marwa,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 22,
        "name": "MAULIDA PUTRI AWALIYAH ",
        "nickname": "Mawl",
        "birth": "Jakarta, 14 May 2003",
        "dream": "Data scientist ",
        "mainDream": "Data Scientist",
        "about": "Just a little girl who has big dreams",
        "achievement1": "Best Board of Executive Officers (BPH) of HMDF Andromeda in 2023",
        "achievement2": "null",
        "achievement3": "null",
        "education": "2021 - 2025 Physics, University of Indonesia ",
        "message": "beli sendal di jogja\nabis itu belok ke bandung, \nyuk? ",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/N59pvB8ZA3E?si=FP9IDjBp_JHJWSiJ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/maulidaaptr",
        "linkedin": "https:\/\/www.linkedin.com\/me?trk=p_mwlite_feed-secondary_nav",
        "twitter": "#",
        "hobby": "singing ",
        "role": "Tiara",
        "image": maul,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 23,
        "name": "MIFTAH FAUZY",
        "nickname": "Oji",
        "birth": "Ciamis, 13 March 2000",
        "dream": "Software Developer, Entrepreneur, Writer",
        "mainDream": "Software Developer",
        "about": "menyusul sambil ngerjain :v",
        "achievement1": "menyusul sambil ngerjain :v",
        "achievement2": "menyusul sambil ngerjain :v",
        "achievement3": "menyusul sambil ngerjain :v",
        "education": "menyusul sambil ngerjain :v",
        "message": "menyusul sambil ngerjain :v",
        "visdream": null,
        "instagram": "#",
        "linkedin": "#",
        "twitter": "#",
        "hobby": "Walking around city, Reading books",
        "role": "Ksatria",
        "image": oji,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 24,
        "name": "MUHAMMAD ALFATIH MUROD",
        "nickname": "Murod",
        "birth": "Tangerang, 20 September 2001",
        "dream": "Sociopreneur, Islamic Socio-finance Expert, Nobel Peace Laureate",
        "mainDream": "Nobel Peace Laureate",
        "about": "Murod is an Islamic economics scholar and sociopreneur who has earned the nickname \"the Warren Buffett of cash waqf\" with outstanding achievements in alleviating poverty throughout the world. With all his achievements and dedication to the world community, in 2050 he won the Nobel Peace Prize and became the first Indonesian to win this award.  Currently, he is spending his old age as a lecturer at an Universitas Indonesia while sharing his experiences in alleviating poverty for the new generation in various cities around the world.",
        "achievement1": "Best of the Best Leader for December 2023",
        "achievement2": "Most Initiative Leader for June and July 2023",
        "achievement3": "Most Productive Leader for October 2023",
        "education": "2020 - 2024: Islamic Economics Science, Universitas Indonesia",
        "message": "Semangat semuanya dalam meraih mimpi dan menjadi versi terbaik masing-masing. Allah bersama kita dan sampai berjumpa kembali di persimpangan jalan Kota Edinburgh.",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/alfath.murod",
        "linkedin": "https:\/\/www.linkedin.com\/in\/muhammadmurod?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        "twitter": "#",
        "hobby": "Reading book",
        "role": "Ksatria",
        "image": murod,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 25,
        "name": "MUHAMMAD ALIF RAMADHAN",
        "nickname": "Alif",
        "birth": "Padang, 31 October 2003",
        "dream": "Gubernur Sumatera Barat, Chess Grandmaster, Guru Besar Ilmu Perundang-Undangan",
        "mainDream": "Akademisi Hukum",
        "about": "Muhammad Alif Ramadhan, familiarly called Alif. He is a student of the Faculty of Law, University of Indonesia. The man who was born in Padang, West Sumatra, is very fond of participating in organizational activities. Throughout his academic journey, Alif has assumed nine Treasurer positions, reaching the pinnacle of his organizational career in his third year, where he held dual Chairmanship roles in two different institutions. This marked the culmination of seven consecutive years in leadership positions. In addition to his extracurricular engagements, Alif has actively contributed to the drafting of national-level legislation. Looking ahead, his vision is to craft a distinctive legal guide for a democratic state unique to Indonesia, aspiring for it to serve as a beacon of inspiration for global civilization.",
        "achievement1": "Drafter of the Regulations of the Capital City Authority concerning Compensation Claims",
        "achievement2": "Drafter of the Amendment to the Law on Tourism",
        "achievement3": "Chairman of the Kongres Mahasiswa at Universitas Indonesia",
        "education": "2021 - 2025: Law, University of Indonesia",
        "message": "selamat merindu. semoga aku, kamu, dan kita menjadi perindu yang berani membawa sebuah rindu menjadi bertemu.",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/glngGaKRUf4?si=ogARkpI5jKvWnOej\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/alif_rama31\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/muhammadaliframadhan\/",
        "twitter": "#",
        "hobby": "Playing Chess",
        "role": "Ksatria",
        "image": alif,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 26,
        "name": "M HAFIDH TAQIYYUDIN",
        "nickname": "Taqi",
        "birth": "Bandar Lampung, 4 September 2002",
        "dream": "Urban Economist, Nobel laureate in Economics, Minister of Transportation of Indonesia",
        "mainDream": "Urban Economist",
        "about": "Hello! I'm Muhammad Hafidh Taqiyyudin, an urban economist deeply passionate about leveraging economic principles to drive sustainable urban development. With a keen interest in research, I focus on areas such as public transportation, housing, and access to essential utilities like water and electricity. Through my work, I aim to foster inclusive growth and improve quality of life in urban communities. When I'm not delving into economic analysis, you can often find me exploring new destinations and immersing myself in diverse cultures—traveling is not just a hobby, but a source of inspiration and learning.",
        "achievement1": "Best of the Best Mapres Ksatiara, March 2024 Edition",
        "achievement2": "null",
        "achievement3": "null",
        "education": "2020 - 2024: Economics, Universitas Indonesia",
        "message": "Halo teman-teman Ksatiara semuanya! Jujur pertemuan dengan kalian adalah salah satu hal yang paling tidak terbayangkan dan tidak terencanakan. Tapi begitulah takdir, mempertemukan dan memisahkan manusia. Selama satu tahun ini, ada begitu banyak kenangan dan juga pelajaran yang didapatkan dari perjalanan bersama kalian. Baik itu secara umum maupun yang didapatkan secara personal dari masing-masing kalian. Semoga pertemanan kita tidak terputus dan berhenti hanya sampai wisuda saja, tetapi lebih jauh sampai akhirnya waktu memisahkan kembali. Kalau seandainya di surga nanti kalian tidak menemukan Taqi, mohon dicari ya dan bawa saya ikut ke sana hehe.\n\nTeruntuk Rumah Kepemimpinan, terima kasih banyak atas begitu banyak pelajaran yang telah diberikan. Terima kasih juga sudah menerima diri ini sebagai rumah kedua.",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/hafidhtaqi",
        "linkedin": "https:\/\/www.linkedin.com\/in\/hafidhtaqiyyudin",
        "twitter": "https:\/\/x.com\/kiyotaqii",
        "hobby": "Traveling, Playing chess",
        "role": "Ksatria",
        "image": taqi,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 27,
        "name": "MUHAMMAD KAFIN NUR",
        "nickname": "Kafin",
        "birth": "Jakarta, 14 September 2002",
        "dream": "Traveler, Media Company Owner",
        "mainDream": "Traveler",
        "about": "\nAn industrial engineering student at the University of Indonesia, thriving in Rumah Kepemimpinan, honing boundless creativity through various activities. Driven to contribute to nation-building through educational equality, aspires to establish a media company offering educational content for Indonesian children nationwide. Admiration for the world's beauty fuels the dream to travel the globe someday.",
        "achievement1": "Student Representative, Board of Trustees Universitas Indonesia (MWA UI UM)",
        "achievement2": "Project Officer, Leadership Exploration and Advancement Program (LEAP) 2024",
        "achievement3": "Finalist of Product Design Competition, CHRONICS UGM",
        "education": "2020 - 2024: Industrial Engineering, Universitas Indonesia",
        "message": "Dear Ksatiara,\n\nSelamat dan semangat menjalani hidup. Ga kebayang betapa kerennya kalian semua ketika keluar kandang. 2 tahun di dalem asrama aja udah keren banget (ini bukan nyamain asrama sama kandang yaa, perumpamaan doang).\n\nTetaplah jadi orang-orang yang baik, ambis, dan segala sifat baik yang kalian miliki selama di asrama. Dan jangan lupa buang jauh-jauh semua kebiasaan buruk kita di asrama yaa. Semoga apa yang kita cita-citakan tercapai semua yaa.",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/kjIypDWjovs?si=BRl9vMgxNqSEcWgZ\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/kafin.nur",
        "linkedin": "https:\/\/www.linkedin.com\/in\/muhammadkafin",
        "twitter": "#",
        "hobby": "Traveling",
        "role": "Ksatria",
        "image": kafin,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 28,
        "name": "MUHAMMAD RAFA ATHALLAH",
        "nickname": "Rafa",
        "birth": "Banjarmasin, 27 September 2003",
        "dream": "Materials Engineering Specialist, Entrepreneur, Executive Director United Nations Environment Programme",
        "mainDream": "Executive Director",
        "about": "Muhammad Rafa Athallah is an undergraduate student majoring in metallurgical and materials engineering at Universitas Indonesia. He is driven by progressive thinking, entrepreneurship, strategic planning, and optimism. His focus lies on metallurgical extraction and biopolymer applications in medicine. In his on-campus organizational experience, he served as Vice General Leader of MPM FTUI 2024. His ultimate goal is to become Executive Director of the United Nations Environment Program.",
        "achievement1": "Elected as Vice General Leacer of MPM FTUI from 4 candidates with a score of 39.625 out of 40. And now leading 41 functionary and 52 staff of MPM FTUI 2024",
        "achievement2": "Presidium of the Musyawarah Kerja X Sidang Komisi Kemahasiswaan Ikatan Keluarga\n",
        "achievement3": "Collaborated and created a Sustainable Students Affair concept called Pembinaan Lanjut for more than 4000 FTUI students with 8 delegates of the FTUI Departmental Student Association (IMD).",
        "education": "2021 - 2025: Metallurgical and Materials Engineering, Universitas Indonesia",
        "message": "Teruntuk Ksatiara Mau bilang terima kasih sebanyak-banyak buat ksatiara karena udh nerima gw jadi bagian dari kalian🥺 Walaupun gw di RK cuma setahun tapi kalo sama kalian rasanya udah kaya bertahun-tahun😫 \n\nTeruntuk squad 4, pesan dari gw sebelum kita bubar jangan mageran bersih-bersih, jaga kesehatan, jangan begadang, jangan makan mie terus (gw juga sih wkwk), inget waktu kalo main fifa, dijaga solatnya, dan pesan2 lainnya. Mungkin squad 4 ga pernah jadi best squad di mapres tapi gw yakin kalian udh jadi best squad di hati gw ANJUYYY\n\nTeruntuk Ksatria (ga nyebut satu2 biar semua kebagian) mau bilang selamat menempuh kehidupan yang baru kelak semoga sukses dan mencapai yang diinginkan1, mungkin selama satu tahun ini banyak cerita yang sedih, senang, dan apalah, walau gw bukan sepuh ataupun senior RK, tapi biarlah gw bisa ikut mengenang segala kisah yang sudah kita lewati selama ini. Kalo kata sheila on 7 \"sebuah kisah klasik\". tapi kalo kata gw \"sebuah kisah luar biasa\" ANJUYY😹\n\nTerakhir pesan dari gw Kehidupan itu seperti gulali, kadang manis, kadang juga klepek-klepek bikin lengket! Tapi ingat, setiap lembaran lengket itu bisa jadi kenangan manis di masa depan! Jadi, nikmati setiap detik klebek-klebeknya bersama-sama! 🍬😄",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/mrafa.ath",
        "linkedin": "https:\/\/www.linkedin.com\/in\/muhammad-rafa-athallah",
        "twitter": "#",
        "hobby": "Cycling, Watching Movie, Reading Novel",
        "role": "Ksatria",
        "image": rafa,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 29,
        "name": "M TAQIYUDDIN AL GHAZI",
        "nickname": "Ghazi",
        "birth": "Jakarta, 11 June 2002",
        "dream": "Humble Person, Machine Learning Engineer, Intellectual",
        "mainDream": "Machine Learning Engineer",
        "about": "Ghazi is an individual with a strong focus on achieving his goals. He possesses a deep passion for mathematics and its applications in the realm of technology. He also likes to try new things that can accelerate his dreams.",
        "achievement1": "Graduated from RK",
        "achievement2": "Research Abroad",
        "achievement3": "Assistant Laboratorium",
        "education": "2021 - 2025: Electrical Engineering, Universitas Indonesia",
        "message": "I hope we don't forget each other",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/Mfu_m_G28vs?si=aDCECp9MDxQU0uf8\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/_ghazimhmd?igsh=aW5wc2wxNGh3ZWdj",
        "linkedin": "https:\/\/www.linkedin.com\/in\/muhammad-taqiyuddin-al-ghazi-30954621a\/",
        "twitter": "#",
        "hobby": "Valorant",
        "role": "Ksatria",
        "image": ghazi,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 30,
        "name": "MUHAMMAD ZAKI FUADI",
        "nickname": "Zaki",
        "birth": "Tasikmalaya, 10 February 2002",
        "dream": "Consultant, Entrepreneur, Storyteller",
        "mainDream": "Storyteller",
        "about": "Through his adventure zaki has developed a deep appreciation for unpredictability of life and approaches every day with a willingness to learn to embrace the unexpected",
        "achievement1": "Fast track master program awardee in Innovation and Design Engineering Universitas Indonesia",
        "achievement2": "Laboratory Assistant Coordinator of Product Development and Innovation Laboratory Universitas Indonesia",
        "achievement3": "1st Winner Intersession Business Case Competition, Universitas Padjajaran",
        "education": "2020 - 2024, Industrial Engineering, Universitas Indonesia",
        "message": "Be attentive in your breath, steps, and actions. ",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/HiHcdD9b0J8?si=ng-YIciv7GyMblSV\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/zakii.fd",
        "linkedin": "https:\/\/www.linkedin.com\/in\/muhammad-fuadi\/ ",
        "twitter": "#",
        "hobby": "Reading, Scrolling, and Strolling",
        "image": zaki,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 31,
        "name": "NABILA FAKHRIN NISA",
        "nickname": "Bila",
        "birth": "Demak, 27 April 2002",
        "dream": "Academician, Philanthropist, Islamic Economics Practitioners ",
        "mainDream": "Academician",
        "about": "A lifetime learner who strives for excellence in a variety of ways and lives by the principle of living minimal.",
        "achievement1": "Research Assistant at Social Security Agency for Employment (BPJS Ketenagakerjaan)",
        "achievement2": "National Islamic Economics Olympiad (NIEO) SEHATI UNDIP 2023",
        "achievement3": "National Business Case Competition (NBCC) ECOFINSC UNDIP 2023",
        "education": "2021 - 2025: Islamic Economics, Universitas Indonesia",
        "message": "Dear Ksatiara, this world isn't our home, so don't make ourselves cozy in it, mari berkontribusi di ranah kita masing-masing untuk Indonesia yang lebih madani >_<",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/nVoasTaUiZ8?si=xoop6_DPF376jjfm\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/instagram.com\/nabiilaafn",
        "linkedin": "https:\/\/linkedin.com\/in\/nabila-fakhrin-nisa",
        "twitter": "#",
        "hobby": "Playing badminton, Listening to fav playlist on spotify",
        "role": "Tiara",
        "image": nabila,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 32,
        "name": "NUR FAJAR SAYYIDUL A",
        "nickname": "Fajar",
        "birth": "Bandung, 23 April 1999",
        "dream": "menyusul sambil ngerjain :v",
        "mainDream": "menyusul sambil ngerjain :v",
        "about": "null",
        "achievement1": "menyusul sambil ngerjain :v",
        "achievement2": "menyusul sambil ngerjain :v",
        "achievement3": "menyusul sambil ngerjain :v",
        "education": "menyusul sambil ngerjain :v",
        "message": "menyusul sambil ngerjain :v",
        "visdream": null,
        "instagram": "#",
        "linkedin": "#",
        "twitter": "#",
        "hobby": "menyusul sambil ngerjain :v",
        "role": "Ksatria",
        "image": fajar,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 33,
        "name": "NUR'AMANIAH 'AL-HAYAT",
        "nickname": "Nia",
        "birth": "Cirebon, 27 Februari 2003",
        "dream": "Professor, Lecturer, Corrosion Engineer ",
        "mainDream": "Professor ",
        "about": "Currently, I am 21 years old. If you don't know me, you might assume that I am withdrawn, but those close to me know that I have a humorous side. My dream is to become a Professor of Metallurgy and Materials Engineering at FTUI.",
        "achievement1": "Finished seminar at the 6th Term",
        "achievement2": "Second Place Winner of the National Scientific Paper Competition 2023 with the theme \"Bersinergi Membangun Negeri dengan Inovasi Terapan Teknologi Menuju Indonesia Maju\" by D-III (HIMAS D-III), Faculty of Engineering, Halu Oleo University (December 2023).",
        "achievement3": "1st Place Winner of the Research Student Project Competition (PKM-GFT) in the Faculty of Engineering, Universitas Indonesia 2023",
        "education": "2021 - 2024 : Metallurgy and Materials Engineering, Universitas Indonesia",
        "message": "Halo temen2 RK gue semuanya 11 bulan bersama kalian adalah hal yg ga pernah terduga, ga nyangka gue bisa bertahan, gue seneng bisa jadi bagian dari RK 11, gue mo minta maaf kalau gue punya salah sama kalian. Gue sayang kalian semuanya. With love Nia^^",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/amaniahalhayat\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/nur-amaniah-al-hayat-892264234\/ ",
        "twitter": "#",
        "hobby": "Reading Novel",
        "role": "Tiara",
        "image": nia,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 34,
        "name": "NURUL AZIZAH",
        "nickname": "Nuy",
        "birth": "Solok, 12 October 2001",
        "dream": "Angel Investor, Educator, Philanthropist ",
        "mainDream": "Educator",
        "about": "Nurul, a passionate creative writer with a deep commitment to making a positive impact in the field of education. Her journey as a writer and volunteer has been shaped by the belief that knowledge and creativity can empower individuals and transform lives. She has great concern about education, people development, journalism, and Islam",
        "achievement1": "Awardee of several scholarships: Marga Pembangunan Jaya, Proyek Masa Depan, Rumah Kepemimpinan, Bank Indonesia, Beasiswa IMAMI 9301, and SMART Scholarship",
        "achievement2": "Partial Funded Delegate of Leap: Malaysia Edition ",
        "achievement3": "\"Hibah Pengmas\" grantee of 5 Projects ",
        "education": "2020 - 2024: Communication, Universitas Indonesia ",
        "message": "kau tau kenapa air menjadi sarang penyakit? karena dia diam dan tidak bergerak. No matter how slow your pace is, keep moving and improve yourself to learn the things you wanna know badly, there is no limitation in learning ",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/wiyoWWFjJrI?si=2YOpkxdgam9Yru_Z\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/nooyyyz",
        "linkedin": "https:\/\/linkedin.com\/in\/nooyyyz",
        "twitter": "#",
        "hobby": "Handling event, watching movies, and making content",
        "role": "Tiara",
        "image": nuy,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 35,
        "name": "RIZKI MONITA BARKAH",
        "nickname": "Monita",
        "birth": "Bogor, 22 August 2001",
        "dream": "Indonesian Business Executive, Business Woman, Philanthopist",
        "mainDream": "Indonesian Business Executive",
        "about": "Hi, It's me, Monita, is an ambitious yet humble woman with a grand vision: to shape Indonesia’s future through a business that combines digital innovation and financial progress with ethical behaviour. \n\nMy passion fuels my journey, and my determination knows no bounds. Weekends are for reflection. I escape to the countryside, where rice fields stretch to the horizon. Here, amidst nature’s serenity, I recharge. I read about successful entrepreneurs, their stories etched in dog-eared pages. Their resilience inspires me—they too started with dreams and determination. Keep dreaming, keep creating, and may my journey be as remarkable as the sunrise over Jakarta’s skyline.",
        "achievement1": "Official Delegates of International Islamic Finance Olympiad & Summer School 2023 (First Runner Up MIG Competition)",
        "achievement2": "Teaching Assistant at FEB UI in 2023\/2024",
        "achievement3": "Got More than 6 Scholarships",
        "education": "2020 - 2024: Islamic Business, Universitas Indonesia",
        "message": "Hi, All!^^ Pertama-tama, saya mau mengucapkan rasa syukur karena menjadi bagian dari RK angkatan 11 dan terima kasih sedalam-dalamnya ke teman-teman Ksatiara semua. RK dan teman-teman Ksatiara sudah menjadi bagian dari proses pembinaan dan saya belajar selama hampir 2 tahun. Momen yang jadi sejarah dalam secuplik kisah hidup saya ini engga akan terlupakan. Selama di RK, saya banyak merasakan momen berkesan dan pembelajaran, terutama dalam menemukan diri saya hingga menguatkan mimpi yang jauh lebih besar. Lompatan-lompatan itu dapat menjadi saksi bagiaman RK telah mengkristalkan semangat itu. Saya telah berani untuk bermimpi besar dengan orang-orang hebat seperti teman-teman yang seringkali menjadi inspirasi saya dalam menemukan kekurangan diri yang perlu saya perbaiki secara continoue tanpa melupakan kelebihan dan kekuatan yang saya miliki. Sekali lagi, terima kasih RK dan ksatiara, harapan saya, semoga semnagat bait terkahir \"Idelisme Kami\" itu tetap hidup.\nSincerely,\nRizki Monita Barkah",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/BxEANVXLV9g?si=DJR-5JMbI3X3CwQW\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/rizkimonitabrkh_",
        "linkedin": "https:\/\/www.linkedin.com\/in\/rizkimonitabarkah",
        "twitter": "#",
        "hobby": "Gardening",
        "role": "Tiara",
        "image": monit,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 36,
        "name": "SALSABILA USMAN PATAMANI",
        "nickname": "Salsa",
        "birth": "Tilamuta, 2 Mei 2004",
        "dream": "Lawyer, Co-Founder SP&P",
        "mainDream": "Lawyer",
        "about": "I'm a cheerful individual who thrives on engaging discussions and attentive listening. I relish the opportunity for meaningful conversations and enjoy delving into diverse topics and issues. With a blend of empathy and legal acumen, I am motivated by the desire to understand others' perspectives and provide solutions. That's why I'm driven to pursue a career as a lawyer.",
        "achievement1": "Finalists Yuris Legal Opinion Competition Universitas PGRI Madiun 2023",
        "achievement2": "Delegates of Universitas Indonesia at the MTQMN 2023",
        "achievement3": "2nd place in Podcast Competition by Woman Days UI 2023",
        "education": "2021 - 2025: Law, Universitas Indonesia",
        "message": "Terima kasih sudah menjadi bagian berharga selama 2 tahun dan seterusnya 💖",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/FIQCMuUtc2E?si=Gr4ltv0-DpU5DH-h\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/salsabiilapt?igsh=NTh4Ym5xMXJ2bXc2",
        "linkedin": "https:\/\/www.linkedin.com\/in\/salsabilausmanpatamani",
        "twitter": "#",
        "hobby": "Writing, listening podcast",
        "role": "Tiara",
        "image": sacil,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 37,
        "name": "SARAH NURUL IZZATI",
        "nickname": "Sarah",
        "birth": "Jakarta, 31 March 2003",
        "dream": "Writer, Lifelong Learner, World Traveler",
        "mainDream": "Writer",
        "about": "Sarah, just an ordinary economics student who suddenly found herself stranded in a blue building on the side of Lenteng Agung road. Little did she know, her predicament would change everything. Indeed, there she learned about becoming the best version of herself. And now, she's still growing. Hopefully, you'll find her in the books you read in the years to come!",
        "achievement1": "Top 10 Data Conquest at Ministry of Finance Data Quest 2023",
        "achievement2": "Top 8 Finalists in the National Short Story Writing Competition, \"Nulis Bareng Teh Jasmine,\" by Universitas Padjadjaran",
        "achievement3": "4th Position of Poster Competition \"Indonesia-Korea Youth Ideas Competition 2023\"",
        "education": "2021 - 2025: Economics, Universitas Indonesia",
        "message": "Rumah Kepemimpinan, Ksatiara, dan segala hal yang mengelilinginya, telah berhasil membuat babak baru dalam cerita kehidupanku. Terima kasih untuk senang, sedih, bahagia, marah, canda, maupun tangisnya di 22 bulan kebelakang. Akan tetapi, aku harap cerita kita tak berhenti di halaman ini. Masih ada lembaran-lembaran berikutnya yang meskipun akan tak sama latarnya, namun semoga masih ada kalian di sana. Tetap menjadi Ksatiara yang selalu \"to infinity and beyond\". Sampai ketemu di persimpangan berikutnya!",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/sarahnurz_",
        "linkedin": "https:\/\/www.linkedin.com\/in\/sarah-nurul-izzati\/",
        "twitter": "#",
        "hobby": "Walking anywhere, even as simple as enjoying the morning shine on the Love Street.",
        "role": "Tiara",
        "image": sarah,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 38,
        "name": "SASMI NANDA WARDANI",
        "nickname": "Sasmi",
        "birth": "Surabaya, 11 September 2001",
        "dream": "Bakery Owner, Auditor",
        "mainDream": "Bakery Owner",
        "about": "null",
        "achievement1": "null",
        "achievement2": "null",
        "achievement3": "null",
        "education": "2020 - 2025: Accounting, Universitas Indonesia",
        "message": "InsyaAllah saudara sampai surga ya, Ksatiara.",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/yp_VbCupmTg?si=SUVjjbP5MQmsE-s5\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/sasminanda",
        "linkedin": "https:\/\/www.linkedin.com\/in\/sasminanda?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app ",
        "twitter": "#",
        "hobby": "Baking",
        "role": "Tiara",
        "image": abdul,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 39,
        "name": "SYIFA KUMALA",
        "nickname": "Syifa",
        "birth": "Sumbawa Besar, 6 October 2001",
        "dream": "Founder of KIMILI foundation, Writer, Nutritionist",
        "mainDream": "Founder of KIMILI foundation",
        "about": "As a nutrition student with a passion for promoting healthy living and understanding psychology, I am driven to increase public awareness about health-related topics through various media platforms. My ultimate goal is to establish the KIMILI foundation, dedicated to ensuring equitable access to healthcare for all communities.",
        "achievement1": "Project Officer of GulaBijak (A social project to against diabetes)",
        "achievement2": "null",
        "achievement3": "null",
        "education": "2020 - 2024: Nutrition, Universitas Indonesia",
        "message": "Terima kasih telah menerima saya menjadi peserta pembinaan RK. Selama dibina, saya menemukan diri saya. Selama dibina, saya mendapatkan teman hidup (teha) yang bisa saya banggakan. Selama dibina, saya menemukan keluarga yang menyenangkan. Sehingga ksatiara menjadi kisah indah dalam hidup saya.",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/629JRQLawTA?si=IhbQOLQINOdAseJK\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/syifikim\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/syifa-kumala\/",
        "twitter": "#",
        "hobby": "Writing, Reading, Listening, Speaking",
        "role": "Tiara",
        "image": sipkum,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 40,
        "name": "SYIFA NURUL AWALIAH",
        "nickname": "Cinul",
        "birth": "Jakarta, 16 July 2002",
        "dream": "CMO Multinational Company, Motivator, Business Mentor",
        "mainDream": "Business Mentor",
        "about": "Syifa is a highly motivated Islamic Business student who excels in business and marketing strategy with more than 3 years of progressive leadership experience through 11 roles in organizations including controller, deputy head of bureau, and manager. The grit, resilience, and agile personality have led Syifa to achieve 5 accomplishments both at the international and national level over the past 2 years. Chosen as the most impactful awardee of Rumah Kepemimpinan scholarships, Syifa aims to create high-performing MSMEs that empower workforces and drive sustainable success in fostering Indonesia Emas by 2045. Syifa is dedicated to utilizing her experience and strategic marketing techniques to support the future workplace and deliver impactful outcomes for Indonesia's economic growth and development by advancing her international relations and business skills.",
        "achievement1": "IISMA 2024 Awardee at Belarusian State University",
        "achievement2": "1st Place Winner of the National Islamic Fintech Olympiad (NIFO)",
        "achievement3": "Runner Up of National Marketing Plan Creativepreneur UMY",
        "education": "2021 - 2025 : Islamic Business, Universitas Indonesia",
        "message": "Haloo, Ksatiara AXI! 2 tahun berasa sangat singkat lantaran tiap harinya diisi dengan kegiatan dan agenda yang bermanfaat. Trimakasii banyak sudah mau menerima gue untuk jadi bagian dari keluarga ini. Gue akan selalu menunggu kabar baik dari kalian, saling bertukar cerita sukses di tiap reuni angkatan. Jangan sombong-sombong yaa sama gue! Jangan sungkan jugaa buat kontak guee!!! ^_^\/",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/LgtD6WcQexo?si=-NOenuZ33Pmdew_a\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/syifanurul_\/",
        "linkedin": "https:\/\/www.linkedin.com\/in\/syifa-nurul-awaliah-5aa1b9215\/",
        "twitter": "#",
        "hobby": "Cycling, Cooking, Blending in with Nature",
        "role": "Tiara",
        "image": cinul,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 41,
        "name": "TITI UMRAN",
        "nickname": "Um",
        "birth": "Pesa, 12 December 2003",
        "dream": "Business women, cool mom, founder of X company",
        "mainDream": "Founder of X company",
        "about": "I'm a cheerful individual who enjoys joking around, although there are times when it's not appropriate. Standing at 160 centimeters tall and weighing 51 kilograms, I embrace all colors, particularly bright and fresh hues. My love for fruit and vegetables knows no bounds, as I enjoy indulging in all types.",
        "achievement1": "Basic Physics Laboratory Assistant 1",
        "achievement2": "Ultrasonic Testing (UT) Level 1 Non-Destructive Testing Certification",
        "achievement3": "Null",
        "education": "2021-2025 : Physics, Universitas Indonesia",
        "message": " Semangat semua dalam meraih jalan berbeda dan berliku kedepannya, jangan pernah berpikir untuk menyerah yaaa",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/avM0lUXCltA?si=MPDchGIcsvyLN14u\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/helloo_um?igsh=cHF6N2oyNXB0dWVp",
        "linkedin": "https:\/\/www.linkedin.com\/in\/titiumran?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        "twitter": "#",
        "hobby": "Reading, watching, cooking",
        "role": "Tiara",
        "image": um,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 42,
        "name": "WAFA RAHMATINA",
        "nickname": "Wafa",
        "birth": "Jakarta, May 30, 2002",
        "dream": "Researcher, Lecturer, CEO of ((something)) Foundation",
        "mainDream": "Lecturer",
        "about": "Wafa is a Public Health student at Universitas Indonesia. She aspires to become a lecturer and also a researcher. She has a big concern regarding Indonesia's health condition, especially related to noncommunicable diseases and maternal health. In the meantime, she enjoys reading books and listening to music.",
        "achievement1": "5th Runner Up Scientific Paper Competition, Musabaqah Tilawatih Quran Mahasiswa Nasional (MTQMN) XVII on November 2023",
        "achievement2": "\nSemifinalist of the Most Outstanding Student Faculty of Public Health at Universitas Indonesia 2023",
        "achievement3": "Food Safety Facilitator Intern at Badan Pengawas Obat dan Makanan 2023",
        "education": "2020 - 2024: Public Health, Universitas Indonesia",
        "message": "Walau kita tidak lagi\nBerlari bersama lagi\nTetapi, doaku ini selalu untukmu\n\nDear Ksatiara,\nTerima kasih atas dua tahun yang sangat berharga\nMari bertemu di waktu QL dan WBS yang sama, walau di tempat yang berbeda :)",
        "visdream": "<iframe width=\"100%\" height=\"315\" src=\"https:\/\/www.youtube.com\/embed\/tpHtDOLjs_o?si=eV40VlinLEP5tiMY\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen><\/iframe>",
        "instagram": "https:\/\/www.instagram.com\/wafarahmaa",
        "linkedin": "https:\/\/www.linkedin.com\/in\/wafarahmatina",
        "twitter": "#",
        "hobby": "Reading book, crying over taylor swift's song",
        "role": "Tiara",
        "image": wafa,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 43,
        "name": "WIDYA NURHIDAYAH TRI K",
        "nickname": "Widya",
        "birth": "Serang, April 22, 2002",
        "dream": "Women Enterpreneur, Angel Investor, State Official",
        "mainDream": "Women Enterpreneur",
        "about": " Hi! I'm just an ordinary person who deeply loves everyone, including myself. My mission is to alleviate pain and spread happiness to all. I hope that my presence can bring a smile to your face, even if only for a brief moment.",
        "achievement1": "Recipient of funding from UI Incubate 2024 PSF Phase for the product \"Cocova\".",
        "achievement2": "Penerima pendanaan Hibah Wirausaha UI produk \"Nabung\"",
        "achievement3": "Ketua pelaksana Kepedulian Masyarakat UI program \"OLI (Outclass Learning Intervention): Kegiatan Pembelajaran Ramah Anak dalam Rangka Meningkatkan Partisipasi Sekolah di Desa Malabae, Lebak, Rangkas\"",
        "education": "2020 - 2024: Nutrition, Universitas Indonesia",
        "message": "Terimakasih banyak Ksatiara atas momen singkat yang sangat berkesan. Terimakasih karena tidak hanya memberikanku banyak kebahagiaan, tetapi juga mengajarkanku untuk selalu berprogres menuju mimpi besarku. Semoga kita semua menjadi orang yang sukses dunia akhirat ❤",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/widyaa_kusuma ",
        "linkedin": "https:\/\/www.linkedin.com\/in\/widyanurhidayah",
        "twitter": "https:\/\/x.com\/widyanrhdh",
        "hobby": "Reading, discuss, sleeping",
        "role": "Tiara",
        "image": widya,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 44,
        "name": "YANEVA AZAHRA RAHMATUNISA",
        "nickname": "Yanev",
        "birth": "Sumedang, August 7, 2002",
        "dream": "Environmental Consultant, Environmental Health Specialist, Philanthropist",
        "mainDream": "Environmental Consultant",
        "about": "Yaneva is a passionate and socially conscious individual deeply committed to advancing environmental health, education, and community well-being. With a strong dedication to addressing environmental challenges and promoting sustainability practices, she actively engages in advocacy efforts. Her biggest dream is to become an environmental consultant. Yaneva excels in effective communication and teamwork, enthusiastically pursues new knowledge, and enjoys engaging in social activities.",
        "achievement1": "Second Place of the Scientific Paper Competition on the Qur'an at MTQMN XVII.",
        "achievement2": "null",
        "achievement3": "null",
        "education": "2021 - 2025: Environmental Health, Universitas Indonesia",
        "message": "Jikalau orang bertanya, siapa sosok yang paling kamu syukuri dan paling kamu hargai kehadirannya di kehidupan kampusmu, aku akan menjawab Rumah Kepemimpinan dan Ksatiara XI. Terima kasih, terima kasih banyak. Sebuah kehormatan bisa menghabiskan 357 hari bersama sosok-sosok paling hangat, hebat, dan luar biasa. Living with the giants is indeed living with the giants. Memori bersama kalian tidak akan pernah aku lupakan. Teruslah terbang lebih tinggi dan lebih jauh. Cerita-cerita hebat kalian di masa depan akan menjadi sesuatu yang sangat aku nanti-nantikan:)",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/yanevaazahra",
        "linkedin": "www.linkedin.com\/in\/yanevaazahra",
        "twitter": "#",
        "hobby": "Reading books, Wacthing movies",
        "role": "Tiara",
        "image": yanev,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 45,
        "name": "ZAKIYAH RASUNA NADIA",
        "nickname": "Zakiyah",
        "birth": "Depok, March 15th, 2003",
        "dream": "Criminal Law Professor",
        "mainDream": "Judge",
        "about": "In everything I've pursued, I've excelled. I believe in continual greatness and strive to take pride in my accomplishments. When I set a goal, I pursue it with passionate determination to succeed. Aspiring to become a judge, I aim to contribute to my country and effect positive change in Indonesian law. Amidst it all, I cherish moments of lighthearted conversation and relaxation.",
        "achievement1": "Manager of Finance at Podium FH UI Board of 2023",
        "achievement2": "Treasurer I of the 27th ALSA National English Competition",
        "achievement3": "Project Officer of Cultural Art Week 2022",
        "education": "2021 - 2025: Law, Universitas Indonesia",
        "message": "It has been a great journey together in RK. Thank you for all the good memories, Ksatiara 11 :)",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/zakiyahrasuna",
        "linkedin": "https:\/\/www.linkedin.com\/in\/zakiyahrasunanadia",
        "twitter": "https:\/\/x.com\/zakrnad",
        "hobby": "Singing",
        "role": "Tiara",
        "image": zakiyah,
        "momen1": null,
        "momen2": null,
        "momen3": null
    },
    {
        "id": 46,
        "name": "ZHARFAN FASYA HIDAYAT ",
        "nickname": "Zharfan",
        "birth": "Jakarta, April 11, 2003",
        "dream": "Data Analyst, Founder Maggot",
        "mainDream": "Data Analyst ",
        "about": "I am someone with strong leadership and team management skills, and I am keenly interested in pursuing a career as a data analyst.",
        "achievement1": "2nd Winner in Muhasaah Tilawatil Quran, MTQ MIPA UI in 2021",
        "achievement2": "2nd Winner in Muhasaah Fahmil Quran, MTQ MIPA UI in 2021",
        "achievement3": "null",
        "education": "2021 - 2025: Physics, Universitas Indonesia ",
        "message": "Semangat dan sukses selalu. Jangan tinggalkan idealisme yg telah diajarkan di RK. Selalu inget bahwa kita sama-sama di bawah lagit asrama. Sahabat sampai surga",
        "visdream": null,
        "instagram": "https:\/\/www.instagram.com\/zharfanfasya_11",
        "linkedin": "Zharfan Fasya",
        "twitter": "#",
        "hobby": "Basketball ",
        "role": "Ksatria",
        "image": zharfan,
        "momen1": null,
        "momen2": null,
        "momen3": null
    }
]